# This is a basic workflow to help you get started with Actions

name: checkhost26

on:
  watch:
    types: started
    
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
  
    - name: prepare
      run: sudo apt install -y nmap

    - name: run
      run: bash ./checkhost26.sh
    - name: push
      uses: github-actions-x/commit@v2.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'Add Deadhost'
        force-add: 'true'
        files: deadhost*
        name: FusionPlmH
        email: leemenhin@gmail.com
        rebase: 'true'
